site_name: Open Symbols
theme:
  name: material
  features:
    - navigation.tabs

nav:
  - Home:
      - Introduction: index.md
      - Arrows: arrows.md
      - Miscellaneous Symbols: misc-symbols.md
      - Dingbats: dingbats.md
      - Geometric Shapes: geometric-shapes.md
      - Math Symbols: math-symbols.md
      - Pictographs: pictographs.md
      - Kaomojis: kaomojis.md
